### ISSUE TITLE
Traduction Widget Conversation 

### ISSUE THREAD

**Issue by mimik0** [pmspr4100/MA-XML-13-FRENCH#1]
Appareil : Mi 11 - v13.0.4 stable

Bonjour, 
Les nouveautés apportent leur lots de nouvelles traduction !  
Dans les widgets, catégorie System UI, quelques que petit trucs par ci par là.

Bonne année et meilleurs voeux en passant !

![IMG_20220105_205710](https://user-images.githubusercontent.com/59457838/148281901-f6cd88e2-08af-4ba7-90fd-14e0a6dfe0db.jpg)

**Comment by pmspr4100** [comment]
Ok corriger
