### ISSUE TITLE
Sound and Google maps/Waze

### ISSUE THREAD

**Issue by Fwifwid971** [pmspr4100/MA-XML-13-FRENCH#2]
Hello, the issue is I can't listen music if Google maps or waze are running. The sound cuts and play , again and again. Even with a call you can't call normally.
Xiaomi 12x weekly builds

**Comment by jblum66** [comment]
Hello. You are on a FRENCH GitHub of xiaomi.eu ROM translation.
So you have to speak French. You have to talk about the translations in French only.
We are not Xiaomi.

Thank you.

**Comment by Fwifwid971** [comment]
Bonjour ok pas de soucis j'ai eu un doutes quand j'ai écris. En tout cas oui le problème un peu gênant. Apparemment ça n'est plus le cas sur la Rom stable mais pour les weekly c'est toujours le caS.
Je vous remercie

**Comment by vitti78** [comment]
Bonjour et tout d'abord, je tenais à vous remercier pour l'immense travail de qualité que vous faites ! 

Je suis actuellement sous la bêta 22.5.18, qui comporte de nombreux bugs dont celui mentionné plus haut. Savez vous s'il m'est possible de revenir sur une release stable même s'il est antérieure à celle de mon Xiaomi Mix 4?

**Comment by jblum66** [comment]
Nous ne traitons ici que les problèmes de traduction. Pour la ROM, il faut aller voir sur xiaomi.eu voire sur Mi.com.
