### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by Fwifwid971** [pmspr4100/MA-XML-13-FRENCH#3]
Kodi doesn't work. I only have a black screen on Xiaomi 12x stable Rom and this IS the same on weekly Rom

**Comment by jblum66** [comment]
Hello. You are on a FRENCH GitHub of xiaomi.eu ROM translation.
So you have to speak French. You have to talk about the translations in French only.
We are not Xiaomi.

Thank you.

**Comment by jblum66** [comment]
Kodi fonctionne en weekly sur mon POCO F3. Par contre il ne démarre jamais sur Mi Pad 5.
De toute façon ce n'est pas le GitHub approprié.
Bonne journée.

**Comment by Fwifwid971** [comment]
Enfaite j'ai compris le soucis. Kodi ne fonctionne pas en 120ghz
