### ISSUE TITLE
Some problems with all google apps

### ISSUE THREAD

**Issue by vitti78** [pmspr4100/MA-XML-13-FRENCH#4]
Bonjour, j'ai téléchargé la mise à jour pour le Xiaomi Mix 4 (22.5.18)  il y a quelques jours et j'ai beaucoup de bugs, notamment concernant les apps google. Youtube, message, Maps, sont quasiment inutilisables et j'ai également de gros soucis de notifications qui ne s'affichent pas, comme sur Whatsapp ou Messenger. Je ne les vois que lorsque j'ouvre les applicatiions mentionnées, alors qu'avant la MAJ je n'avais aucun souci! 

Savez vous s'il m'est possible de revenir sur une release stable même s'il est antérieure à celle actuellement sur mon Xiaomi Mix 4?
Merci d'avance pour votre aide.

**Comment by mimik0** [comment]
Slt !
Je crois que t'as pas tout compris....
T'es sur le git qui ne concerne que la traduction fr.
Personne ne répondra à ta question cherche ailleur 😉
