### ISSUE TITLE
Report d'une notification "Répété pendant X heures"

### ISSUE THREAD

**Issue by Monakiel** [pmspr4100/MA-XML-13-FRENCH#5]
Bonjour,

Quand on appuie sur le réveil (z) d'une notification, il est écrit 

> "Répété pendant 1 heure"

Je pense que la bonne traduction est :
`"Répétée dans 1 heure"` (si on parle de la notification qui est répétée)
`"Répéter dans 1 heure"` (si on parle de manière générale)

En tout cas, le 'pendant' est à corriger en **'dans'** et le 'Répété' en soit **'Répétée' soit 'Répéter'**. A noter que si en anglais c'est 'Repeated' alors la trad sera 'Répétée'. Si c'est 'Repeat' alors ce sera 'Répéter'.
_(contrairement à ma bulle où j'avais laissé 'Répété' dans un premier temps)_

![1663224863414](https://user-images.githubusercontent.com/35536198/190335419-b9142d90-c44c-4b9a-ba94-41ed4a090f2e.jpg)

**Comment by jblum66** [comment]
Bonjour,
Le terme original est `Snoozed for 1 hour`, donc on pourrait théoriquement mettre `Mis en veille pendant 1 heure`. Mais je pense que le terme `Répéter dans 1 heure` convient mieux ; et il est plus court.
Je change ça.

**Comment by Monakiel** [comment]
Bonjour oui :)
Si le terme est conjugué, alors c'est `Répétée `qu'il faudrait mettre car c'est la notification qui est snoozed/répétée. L'action a déjà été faite et donc on nous indique que la notif sera répétée.

`Mise en veille` n'est clairement pas approprié. `Reportée` peut aussi être une bonne traduction.

Finalement, `Répétée dans 1 heure` semble être la traduction la plus adaptée.

**Comment by jblum66** [comment]
OK
