### ISSUE TITLE
Message sending doesn't work

### ISSUE THREAD

**Issue by Micky-lkf-77** [pmspr4100/MA-XML-13-FRENCH#6]
When i sens a message with all message application like Google message, native application it doesn't work.
For mms this error : network not ready, Try again
For SMS: message not send, push to retry
Any solutions ?
Thanks.
Mickaël.

**Comment by jblum66** [comment]
Hi Mickaël,
This repository is about ROM translation. You should ask on https://c.mi.com/fr/
Regards.

**Comment by Micky-lkf-77** [comment]
Ok, thanks.
Mickaël.

⁣Télécharger BlueMail pour Android ​

Le 26 sept. 2022, 13:16, à 13:16, jb66 ***@***.***> a écrit:
