### ISSUE TITLE
pb trad

### ISSUE THREAD

**Issue by kevin2008-01** [pmspr4100/MA-XML-13-FRENCH#8]
Bonjour, dans paramétres, mon appareil "detailled info ans specs" à traduire. merci et bon courage. rom 14.023.2.6 DEV pour Mi11

**Comment by jblum66** [comment]
Bonjour, apparemment tu utilises MIUI 14 et non MIUI 13. Je ne trouve pas ce message dans MIUI 13.

> Bonjour, dans paramétres, mon appareil "detailled info ans specs" à traduire. merci et bon courage. rom 14.023.2.6 DEV pour Mi11

**Comment by pmspr4100** [comment]
Correction OK sur MIUI 14.
